import Foundation

/// A response from the Responses API.
public struct Response: Codable, Sendable {
    /// The unique identifier for this response.
    public let id: String
    /// The object type, always `"response"`.
    public let object: String
    /// The Unix timestamp (in seconds) of when the response was created.
    public let createdAt: Int
    /// The model used to generate the response.
    public let model: String
    /// The output items generated by the model.
    public let output: [ResponseOutputItem]
    /// The status of the response (e.g. `"completed"`, `"failed"`).
    public let status: String
    /// Token usage statistics for the response.
    public let usage: ResponseUsage?
    /// Arbitrary key-value metadata attached to the response.
    public let metadata: [String: String]?
}

/// An output item in a response.
public struct ResponseOutputItem: Codable, Sendable {
    /// The type of output item (e.g. `"message"`).
    public let type: String
    /// The unique identifier for this output item.
    public let id: String?
    /// The role of the output item author (e.g. `"assistant"`).
    public let role: String?
    /// The content parts of this output item.
    public let content: [ResponseContentPart]?
}

/// A content part in a response output item.
public struct ResponseContentPart: Codable, Sendable {
    /// The type of content part (e.g. `"output_text"`).
    public let type: String
    /// The text content, if this is a text part.
    public let text: String?
}

/// Token usage statistics for a response.
public struct ResponseUsage: Codable, Sendable {
    /// The number of input tokens used.
    public let inputTokens: Int
    /// The number of output tokens generated.
    public let outputTokens: Int
    /// The total number of tokens used.
    public let totalTokens: Int
}

/// Input for the Responses API.
///
/// Can be a simple text string or an array of messages.
public enum ResponseInput: Encodable, Sendable {
    /// A simple text input.
    case text(String)
    /// An array of input messages.
    case messages([ResponseInputMessage])

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .text(let text):
            try container.encode(text)
        case .messages(let messages):
            try container.encode(messages)
        }
    }
}

/// A message in the Responses API input.
public struct ResponseInputMessage: Encodable, Sendable {
    /// The role of the message author (e.g. `"user"`, `"system"`).
    public let role: String
    /// The text content of the message.
    public let content: String

    /// Creates a new input message.
    ///
    /// - Parameters:
    ///   - role: The role of the message author.
    ///   - content: The text content of the message.
    public init(role: String, content: String) {
        self.role = role
        self.content = content
    }
}

/// Parameters for creating a response.
struct ResponseCreateParams: Encodable, Sendable {
    let model: String
    let input: ResponseInput
    let instructions: String?
    let maxOutputTokens: Int?
    let temperature: Double?
    let topP: Double?
    let stream: Bool?
    let store: Bool?
    let metadata: [String: String]?
}

/// A streamed event from the Responses API.
public struct ResponseStreamEvent: Codable, Sendable {
    /// The event type (e.g. `"response.created"`, `"response.done"`).
    public let type: String
    /// The response object, if included in this event.
    public let response: Response?
}
