import Foundation

/// Token usage information returned by many API endpoints.
///
/// Mirrors the Python SDK's `CompletionUsage`, including the breakdown of
/// prompt and completion tokens. `promptTokensDetails.cachedTokens` reports how
/// many prompt tokens were served from the prompt cache (relevant for cost
/// tracking with [prompt caching](https://platform.openai.com/docs/guides/prompt-caching)).
public struct Usage: Codable, Sendable {
    /// Number of tokens in the prompt.
    public let promptTokens: Int
    /// Number of tokens in the generated completion, when applicable.
    public let completionTokens: Int?
    /// Total number of tokens used (prompt + completion).
    public let totalTokens: Int
    /// Breakdown of tokens used in the prompt.
    public let promptTokensDetails: PromptTokensDetails?
    /// Breakdown of tokens used in the completion.
    public let completionTokensDetails: CompletionTokensDetails?

    /// Breakdown of tokens used in the prompt.
    public struct PromptTokensDetails: Codable, Sendable {
        /// Cached tokens present in the prompt.
        public let cachedTokens: Int?
        /// Audio input tokens present in the prompt.
        public let audioTokens: Int?

        public init(cachedTokens: Int? = nil, audioTokens: Int? = nil) {
            self.cachedTokens = cachedTokens
            self.audioTokens = audioTokens
        }
    }

    /// Breakdown of tokens used in a completion.
    public struct CompletionTokensDetails: Codable, Sendable {
        /// Tokens generated by the model for reasoning.
        public let reasoningTokens: Int?
        /// Audio tokens generated by the model.
        public let audioTokens: Int?
        /// When using Predicted Outputs, tokens in the prediction that appeared in the completion.
        public let acceptedPredictionTokens: Int?
        /// When using Predicted Outputs, tokens in the prediction that did not appear in the completion.
        public let rejectedPredictionTokens: Int?

        public init(
            reasoningTokens: Int? = nil,
            audioTokens: Int? = nil,
            acceptedPredictionTokens: Int? = nil,
            rejectedPredictionTokens: Int? = nil
        ) {
            self.reasoningTokens = reasoningTokens
            self.audioTokens = audioTokens
            self.acceptedPredictionTokens = acceptedPredictionTokens
            self.rejectedPredictionTokens = rejectedPredictionTokens
        }
    }

    public init(
        promptTokens: Int,
        completionTokens: Int? = nil,
        totalTokens: Int,
        promptTokensDetails: PromptTokensDetails? = nil,
        completionTokensDetails: CompletionTokensDetails? = nil
    ) {
        self.promptTokens = promptTokens
        self.completionTokens = completionTokens
        self.totalTokens = totalTokens
        self.promptTokensDetails = promptTokensDetails
        self.completionTokensDetails = completionTokensDetails
    }
}
